# Mockfog Application Definition

application_definition:
  - name: application
    container_name: application
    docker_image: mockfogoverload/heartrate_example:final
    expose: 30444
    ports: 30444:30444

  - name: generator
    container_name: generators
    docker_image: mockfogoverload/generators:final
    expose: 20201
    ports: 20201:8080
